### ISSUE TITLE
Problems installing the WER toolkit

### ISSUE THREAD

**Issue by Yuki-jy** [facebookresearch/MMCSG#3]
While installing the wer evaluation kit, we encountered the following problem as shown in the image. We guess it has something to do with the version of the C compiler. What is the official version of gcc and cmake used? And is this error related to the version of external libraries glog, folly?
![Snipaste_2024-03-10_13-56-23](https://github.com/facebookresearch/MMCSG/assets/58199609/f65e51d7-3c9b-4b1d-9600-08ceed71c610)

**Comment by zmolikova** [comment]
Thank you for reporting!

We compiled with g++ 9.4.0. These are the versions of the libraries installed by conda, which we tested with:

```
glog 0.6.0
eigen 3.4.0
folly 2024.02.12.00
```
Can you try with these and report back?

**Comment by zmolikova** [comment]
I just added the specification of the versions of these libraries to `requirements.txt`.

**Comment by AlenLHB** [comment]
We use the versions above and another question is like following:

MultiTalkerEditDistance.h:114:10:error: 'Tensor' innamespace ‘Eigen ’ dose not name a template type
114 |  Eigen::Tensor<float, 3, Eigen::RowMajor> scores_;
MultiTalkerEditDistance.h:115:10:error: 'Tensor' innamespace ‘Eigen ’ dose not name a template type
115 |  Eigen::Tensor<long, 4, Eigen::RowMajor> backtraces_;

so how can we solve it? Thank you

**Comment by zmolikova** [comment]
Can you confirm whether this file exists in your conda environment?
`${CONDA_PREFIX}/include/eigen3/unsupported/Eigen/CXX11/src/Tensor/Tensor.h`

And perhaps can you share the entire output of the compiler?

**Comment by AlenLHB** [comment]
${CONDA_PREFIX}/include/eigen3/unsupported/Eigen/CXX11/src/Tensor/Tensor.h 
This file really exists in my conda environment 
![Tensor](https://github.com/facebookresearch/MMCSG/assets/72533577/8f7d2f3c-ebba-4b70-a1ce-25b655a9e472)
![error](https://github.com/facebookresearch/MMCSG/assets/72533577/a74b9d6d-1750-41d8-a37f-f6f5c3a65afa)

**Comment by zmolikova** [comment]
Is it possible that you have two versions of eigen installed in `$CONDA_PREFIX/include/Eigen` and `$CONDA_PREFIX/include/eigen3`?

The code lines in the screenshot look like [Eigen 3.2](https://gitlab.com/libeigen/eigen/-/blob/3.2/Eigen/src/Core/products/GeneralBlockPanelKernel.h) rather than [Eigen 3.4](https://gitlab.com/libeigen/eigen/-/blob/3.4/Eigen/src/Core/products/GeneralBlockPanelKernel.h). 

If that is the case, you could try to remove (or rename) the `$CONDA_PREFIX/include/Eigen` one. Or start the installation with the specified versions from a clean environment, if you haven't done so previously.

**Comment by zmolikova** [comment]
Let me know if there is any progress with the installation issues. We would like to help to get this working.

**Comment by Yuki-jy** [comment]
Thank you. We solved the problem after aligning all versions of dependent libraries and g++. It might have a strong dependency with the compiler version, python version and the version of the dependency libraries.

**Comment by zmolikova** [comment]
Good to hear. I am closing the issue for now. Feel free to re-open or open a new one if there are any further issues.
