### ISSUE TITLE
problems about eigen

### ISSUE THREAD

**Issue by tang-yu-feng** [facebookresearch/MMCSG#5]
I ran the command 'pip install eigen==3.4.0', there come the error 'ERROR: Could not find a version that satisfies the requirement eigen==3.4 (from versions: 0.1.1)
ERROR: No matching distribution found for eigen==3.4' .  I searched on https://pypi.org/search, there is only 0.1.1.

**Comment by zmolikova** [comment]
Thanks for reporting the issue.
Is it possible for you to use conda instead of installing with pip? That's what we tested the code with.

**Comment by tang-yu-feng** [comment]
Thanks for your reply. 'conda install' worked.
